language: python
sudo: required
python:
- '3.8'
install: pip install -r requirements.txt
script: nosetests test/unit/test_skeleton.py
before_deploy:
- "./make_manifest.sh test"
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.de.a9s.eu
  username: ripocipur.norefosod@mentonit.net
  organization: ripocipur_norefosod_mentonit_net
  space: test
  on:
    branch: main
    python: '3.8'
  password:
    secure: l3a/XH8TzZsVdl/1pdnHsnkRFLXSiVULffubC5VfBP4eAUGl5Sv0mDiRCZXnVJytmkGT6+q0adaJgXJo/RIcj1YXjxJobOZ520SL1U+rQYuYa97y9Ww3vazpz5+5N58s624DbeUfS3VSbXzvJUfQ87N5N2DUc8J5h+pZcZTs9p5AXlIHFEBQoAJq67Wrk+usLSO9QMuMjklYH+jKTp1613lTIbJec6diAjS3pm6NXE8IJEC4cteFqk+TbP1MIk4QY+sTfm2JGuVEc9DFZlJJT8v3m2mZYIhlP3alPrV4q9SWciFeOmZaG84OFKDe5Fs7AvfaTY6BVvIOWbyP0nB4nPQkN64iaWtzkDvgyrK1bouqcenEC3iSASZZNxN6GaU9wUKIgljh8lyLQSyqD6Kc+R3s8QQAcsZzrt92yqnzvOEDDAX8fXhwzanwjEMsKsnGMi5O+ybz+JPUWoTyiboVmBfEUp7zz92tHaqZSN1VbXqfh5Wwbss+lFYW0vrg8ipfLJJUM0GS46iY6747BlTM42wE3szc6xY3D1ap0dNxjOX8fS2uNrXgSwedeGS8qMy2QqROe96uMm3yIWEsF/3DYVsQ56lxkNdlBhqKU8+RyOJBC6Pg4L3Iouy+DjS3pjULD/qPCA6cdG/mqhG266uqFuBF7ZfiKX/cIheTgpbmsvo=
